spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://transactionUser:UXgUUsuTPJ@mongodbcluster.dfr8yly.mongodb.net/TransactionDB?appName=MongoDBCluster}
spring.data.mongodb.database=TransactionDB
#spring.data.mongodb.auto-index-creation=true
server.port=${PORT:10000}